### ISSUE TITLE
Feedback: The issue seems to be fixed 

### ISSUE THREAD

**Issue by Nicoconot** [dmnct/spyro-fix#2]
I ran Spyro for the first time on Proton 4.11(so not the most recent) on  Linux Mint and I had no problem with the cutscenes. My specs:
OS: Linux Mint 20.2
KERNEL: 5.4.0-90-generic
CPU: Intel Core i7-4710HQ @ 2.50GHz
GPU: NVIDIA NVIDIA GeForce GTX 970M
GPU DRIVER: NVIDIA 470.82.00
RAM: 12 GB

**Comment by Errant-4** [comment]
Hi, thank you for the report. I am mostly looking for positive sightings of the language bug, since from what I could tell it has always worked correctly for some users, according to the protondb reports. 
I actually have no criteria currently established for how/when I could consider the issue resolved for good (not that I really need to, I was just curious)

**Comment by acidflare** [comment]
The issue seems to be tied directly to ProtonGE. The issue doesn't appear in Proton 6.3-8 however xinput controllers don't work with it despite steam correctly using the controller, so stuck with using ProtonGE to play using a controller. both ProtonGE 7.0RC3 and 6.21-2 have the audio issue, I don't think it's random audio track selection though. In the beginning of Spyro2 the audio is in Polish, any cut scene after that uses Spanish. The chosen language in steam is English.

Your script worked without any issues. Once the script completed I started the game again and started the games in slot 2 which was unused before hand and the videos played in English.
